### ISSUE TITLE
New auto tools available.

### ISSUE THREAD

**Issue by RaveGun** [micas-pro/rapidradio#1]
Hello,

Compile does not work now because the available autotools is now 1.14.

**Comment by micas-pro** [comment]
Hi, 

Thank you, I'll fix it soon!

Cheers,
micas-pro

**Comment by adarshsmonippally** [comment]
Micas Hello,

I would be happy if you can fix the new auto tools as it is in 1.15 now.
I tried a lot myself before reaching to you.

Please do me a favour.

Thanks in advance.

**Comment by RaveGun** [comment]
I guess that this project and anything related to it is since a long time death.

I will close this issue.
